#Name of Workflow
name: Hello2 workflow
on:
#When to run when someone pushes on Main branch then it triggers
  push:
    branches:
      - main
Jobs:
#Name of Job
  great:
  #This is Git hub Runner ( Server where Jobs run), each jobs runs on a runner here there are 2 jobs
    runs on: ubuntu-latest
    steps:
      - name: say hello to users
        run: echo "hello Mate"
      - name: say hello to username
        run: echo " Hellp $User"
