name: Hello2 workflow

on:
  push:
    branches:
      - main

jobs:
  # First Job
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: say hello to users
        run: echo "hello Mate how you doing?"

      - name: say hello to username
        run: echo "Hello $USER"

  # Second Job
  details:
    runs-on: ubuntu-latest

    steps:
      - name: docker and python version
        run: docker --version && python --version
